ConvertVarForMatlab <- function(varToConvert) {
    #sub all "." and "_"
    converted.var <- gsub("\\.", "_", varToConvert)
    
    return(converted.var)
}

create_matlab_model_function <- function(variables, 
                                         parameters, 
                                         diffEquations, 
                                         parameterValues, 
                                         additionalEqns, 
                                         ICs, 
                                         timeScaleBool, 
                                         timeScaleValue,
                                         timeStart,
                                         timeEnd,
                                         timeStep){
  # Inputs:
  #   @variables - vector of species names in model
  #   @parameters - vector of names of parameters in model
  #   @diffEquations - vector of text differential equations
  #   @parameterValues - vector of param values corresponding to parameters
  #   @additionalEqns - vector of additional equations user created
  #   @ICs - vector of species initial condition values
  #   @timeScaleBool - boolean if time scale exists
  #   @timeScaleValue - numeric value of scale value
  #   @timeStart - time model starts
  #   @timeEnd  - time model ends
  #   @timeStep - step between start and end times
  
  # Variable Conversion --------------------------------------------------------
  #convert Variables to matlab format if necessary
  # browser()
  print("Create Matlab Script Function")
  print(variables)
  print(parameters)
  print(diffEquations)
  variables <- sapply(variables, ConvertVarForMatlab, USE.NAMES = FALSE)
  parameters <- sapply(parameters, ConvertVarForMatlab, USE.NAMES = FALSE)
  equations <- sapply(diffEquations, ConvertVarForMatlab, USE.NAMES = FALSE)
  
  # Code Header Info -----------------------------------------------------------
  h.open <- paste0("Code generated by BioModME")
  h.date <- paste0("Created on ", Sys.time())
  # h.units <- paste0("Unit output will go here.")
  # h.eqns <- paste0("Reaction equations will go here")
  # h.io   <- paste0("Model IO will go here")
  
  header <- paste0("% ", h.open, "\n",
                   "% ", h.date, "\n",
                   # "% ", h.units, "\n",
                   # "% ", h.eqns, "\n",
                   # "% ", h.io, "\n",
                   "% ", "-------------------------------", "\n\n")
  
  # Driver -------------------------------------------------------------------
  driver <- paste0("tspan = ", timeStart, ":", timeStep, ":", timeEnd, ";\n")
  driver <- paste0(driver, "ICs = Initial_Conditions();\n")
  driver <- paste0(driver, "par = pars();\n")
  
  # add ODE options here in the future
  
  driver <- paste0(driver, "myModel = @(t,y)(model(t, y, par));\n")
  driver <- paste0(driver, "[time, Y] = ode15s(myModel, tspan, ICs);\n")
  driver <- paste0(driver, "plot(time, Y);\n")

  # Model Function -------------------------------------------------------------
  # print start of model function to matlab script including variable unpacking
  model_function <- "function dy = model(t, y, par)\n"
  for (var_num in seq(length(variables))) {
      line_to_add <- paste0("\t",variables[var_num], "=y(", var_num, ");\n")
      model_function <- paste0(model_function, line_to_add)
  }
  
  # paste parameters  to matlab script
  model_function <- paste0(model_function, "\n%Parameters\n")
  for (par_num in seq(length(parameters))) {
      line_to_add <- paste0("\t",
                            parameters[par_num],
                            "=", 
                            "par(", 
                            par_num, 
                            ");\n")
      model_function <- paste0(model_function, line_to_add)
  }
  
  #paste rate equations to matlab script
  # Extract additional eqns
  additionalEqns <- unname(sapply(additionalEqns,
                                  get,
                                  x = "Equation"))
  if (length(additionalEqns) > 0) {
      model_function <- paste0(model_function, "\n%Custom Equations\n")
      for (i in seq(length(additionalEqns))) {
          line_to_add <- paste0("\t", additionalEqns[i], ";\n")
          model_function <- paste0(model_function, line_to_add)
      } 
  }
  
  
  #paste differential equations to matlab script
  model_function <- paste0(model_function, "\n%Differential Equations\n")
  for (eqn_num in seq(length(equations))) {
      line_to_add <- paste0("\t", 
                            "d", 
                            variables[eqn_num], 
                            "=", 
                            equations[eqn_num], 
                            ";\n")
      model_function <- paste0(model_function, 
                               line_to_add)
  }
  
  #package up differential equations to output variable dy
  model_function <- paste0(model_function, 
                           "\n%Package Differential Equations to Output\n")
  for (i in seq(length(equations))) {
      line_to_add <- paste0("\t", "dy(", i, ") = ", "d", variables[i], ";\n")
      model_function <- paste0(model_function, line_to_add)
  }
  ending_line <- ifelse(timeScaleBool, 
                        paste0("\tdy=", 
                               timeScaleValue,
                               "*dy';\n",
                               "end\n"), 
                        paste0("\tdy=dy';\n", "end\n"))
  model_function <- paste0(model_function, ending_line)
  
  # Parameters -----------------------------------------------------------------
  # generate parameter function that stores all parameters of the equation
  parameter_function <- "function p = pars()\n"
  
  for (par_num in seq(length(parameters))) {
      line_to_add <- paste0("\tp(", 
                            par_num, ")=", 
                            parameterValues[par_num], 
                            ";\t%", parameters[par_num]   
                            ,"\n")
      parameter_function <- paste0(parameter_function, 
                                   line_to_add)
  }
  
  parameter_function <- paste0(parameter_function, 
                               "end")
  
  model_function <- paste0(model_function, 
                           "\n\n", 
                           parameter_function)
  
  # Initial Conditions ---------------------------------------------------------
  
  # Add matlab function for initial conditions
  IC_function <- "function y0 = Initial_Conditions()\n"
  
  for (i in seq(length(ICs))) {
      line_to_add <- paste0("\t", 
                            "y0(", 
                            i, 
                            ")=", 
                            ICs[i], 
                            ";\t%", 
                            variables[i], 
                            "\n")
      
      IC_function <- paste0(IC_function, line_to_add)
  }
  IC_function <- paste0(IC_function, "end")
  
  model_function <- paste0(model_function, "\n\n", IC_function)

  output <- paste0(header, driver, "\n" , model_function)
  
  return(output)
}