# Build a single-file C++ program that simulates the model with Boost.Odeint
# (header-only — much easier setup than SUNDIALS) and writes a CSV of the
# trajectory to stdout. Argument names match the other write_*.R helpers so
# the download handler can pass the same vector of inputs.

# C++ identifiers allow underscores but not dots, so we just replace `.`
# with `_`, identical to the Julia/Python sanitization.
.cpp_sanitize_name <- function(name) {
  gsub("\\.", "_", as.character(name))
}

.cpp_sanitize_expr <- function(expr) {
  gsub("\\.", "_", as.character(expr))
}

# ---- Section: state names array ----------------------------------------------
cpp_state_names <- function(species, line_width = 80) {
  body <- vapply(seq_along(species), function(i) {
    sep <- if (i != length(species)) "," else ""
    paste0("    \"", species[i], "\"", sep)
  }, character(1))
  paste0(
    "static const std::array<const char*, ", length(species), "> kStateNames = {\n",
    paste(body, collapse = "\n"), "\n",
    "};"
  )
}

# ---- Section: initial state --------------------------------------------------
cpp_initial_state <- function(species, ICs, comments) {
  lines <- vapply(seq_along(species), function(i) {
    cmt <- if (length(comments) >= i && nzchar(comments[i])) {
      paste0("  // ", comments[i])
    } else ""
    paste0("    y[", i - 1, "] = ", ICs[i], ";", cmt, "  // ", species[i])
  }, character(1))
  paste0(
    "state_t initial_state() {\n",
    "    state_t y;\n",
    paste(lines, collapse = "\n"), "\n",
    "    return y;\n",
    "}"
  )
}

# ---- Section: parameter struct -----------------------------------------------
cpp_params <- function(param_names, defaults_values, comments) {
  lines <- vapply(seq_along(param_names), function(i) {
    cmt <- if (length(comments) >= i && nzchar(comments[i])) {
      paste0("  // ", comments[i])
    } else ""
    paste0("    double ", param_names[i], " = ", defaults_values[i], ";", cmt)
  }, character(1))
  paste0(
    "struct Params {\n",
    paste(lines, collapse = "\n"), "\n",
    "};"
  )
}

# ---- Section: ODE functor ----------------------------------------------------
cpp_diff_equations <- function(species, parameters, diffeqs, rules) {
  unpack_state <- vapply(seq_along(species), function(i) {
    paste0("        const double ", species[i], " = u[", i - 1, "];")
  }, character(1))
  unpack_params <- vapply(parameters, function(pname) {
    paste0("        const double ", pname, " = p_.", pname, ";")
  }, character(1))
  rule_lines <- if (length(rules) > 0) {
    vapply(rules, function(r) paste0("        ", r, ";"), character(1))
  } else character(0)
  diff_lines <- vapply(seq_along(species), function(i) {
    paste0("        d[", i - 1, "] = ", diffeqs[i], ";")
  }, character(1))

  rules_block <- if (length(rule_lines) > 0) {
    paste0("\n        // Rules / custom equations\n",
           paste(rule_lines, collapse = "\n"))
  } else ""

  paste0(
    "struct Model {\n",
    "    Params p_;\n",
    "    void operator()(const state_t& u, state_t& d, double /*t*/) const {\n",
    "        // Unpack state variables\n",
    paste(unpack_state, collapse = "\n"), "\n\n",
    "        // Unpack parameter variables\n",
    paste(unpack_params, collapse = "\n"),
    rules_block, "\n\n",
    "        // Differential equations\n",
    paste(diff_lines, collapse = "\n"), "\n",
    "    }\n",
    "};"
  )
}

# ---- Orchestrator ------------------------------------------------------------
cpp_generate_script <- function(species,
                                parameters,
                                diffEquations,
                                parameterValues,
                                parameterComments,
                                rules,
                                ICs,
                                speciesComments,
                                timeStart,
                                timeEnd) {

  species    <- vapply(species,    .cpp_sanitize_name, character(1), USE.NAMES = FALSE)
  parameters <- vapply(parameters, .cpp_sanitize_name, character(1), USE.NAMES = FALSE)
  diffEquations <- vapply(diffEquations, .cpp_sanitize_expr, character(1), USE.NAMES = FALSE)
  rules <- if (length(rules) > 0) {
    vapply(rules, .cpp_sanitize_expr, character(1), USE.NAMES = FALSE)
  } else character(0)

  n_species <- length(species)

  header <- paste0(
    "// Code generated by BioModME\n",
    "// Created on ", Sys.time(), "\n",
    "// -----------------------------\n",
    "//\n",
    "// Build:  g++ -std=c++17 -O2 model.cpp -o model\n",
    "// Run:    ./model > output.csv\n",
    "//\n",
    "// Requires Boost (header-only). Install with:\n",
    "//   apt install libboost-dev          (Debian/Ubuntu)\n",
    "//   brew install boost                (macOS)\n",
    "//   vcpkg install boost-numeric-odeint (Windows)\n",
    "//\n",
    "// Quick plot of the resulting CSV with gnuplot:\n",
    "//   gnuplot -persist -e \"set datafile separator ','; \\\n",
    "//     set key autotitle columnhead; plot for [i=2:", n_species + 1,
                "] 'output.csv' using 1:i with lines\"\n",
    "\n",
    "#include <array>\n",
    "#include <iomanip>\n",
    "#include <iostream>\n",
    "#include <vector>\n",
    "#include <boost/numeric/odeint.hpp>\n",
    "\n",
    "namespace odeint = boost::numeric::odeint;\n",
    "\n",
    "using state_t = std::array<double, ", n_species, ">;"
  )

  state_names_block <- cpp_state_names(species)
  init_state_block  <- cpp_initial_state(species, ICs, speciesComments)
  params_block      <- cpp_params(parameters, parameterValues, parameterComments)
  ode_block         <- cpp_diff_equations(species, parameters, diffEquations, rules)

  driver <- paste0(
    "int main() {\n",
    "    state_t y = initial_state();\n",
    "    Model model;  // override defaults like:  model.p_.k_f1 = 1.5;\n",
    "\n",
    "    const double t_start = ", timeStart, ".0;\n",
    "    const double t_end   = ", timeEnd, ".0;\n",
    "    const double dt0     = (t_end - t_start) / 1000.0;  // initial step\n",
    "\n",
    "    std::vector<double> times;\n",
    "    std::vector<state_t> states;\n",
    "    auto observer = [&](const state_t& s, double t) {\n",
    "        times.push_back(t);\n",
    "        states.push_back(s);\n",
    "    };\n",
    "\n",
    "    // Adaptive Runge-Kutta-Cash-Karp with absolute / relative tolerances\n",
    "    // suited to typical biochemistry. For very stiff systems consider\n",
    "    // odeint::rosenbrock4 (requires Boost.uBLAS).\n",
    "    using stepper_t = odeint::runge_kutta_cash_karp54<state_t>;\n",
    "    odeint::integrate_adaptive(\n",
    "        odeint::make_controlled<stepper_t>(1e-9, 1e-6),\n",
    "        model, y, t_start, t_end, dt0, observer\n",
    "    );\n",
    "\n",
    "    // CSV output: time + every species column\n",
    "    std::cout << \"time\";\n",
    "    for (auto name : kStateNames) std::cout << \",\" << name;\n",
    "    std::cout << \"\\n\";\n",
    "    std::cout << std::setprecision(10);\n",
    "    for (std::size_t i = 0; i < times.size(); ++i) {\n",
    "        std::cout << times[i];\n",
    "        for (double v : states[i]) std::cout << \",\" << v;\n",
    "        std::cout << \"\\n\";\n",
    "    }\n",
    "    return 0;\n",
    "}"
  )

  paste0(
    header,             "\n\n",
    state_names_block,  "\n\n",
    init_state_block,   "\n\n",
    params_block,       "\n\n",
    ode_block,          "\n\n",
    driver,             "\n"
  )
}
